name: monolith

services:
  traefik:
    image: traefik:3.4
    profiles:
      - with_traefik
    command:
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80/tcp
      - --entrypoints.websecure.address=:443/tcp
      - --entrypoints.websecure.http.tls.certresolver=le
      - --certificatesresolvers.le.acme.tlschallenge=true
      - --certificatesresolvers.le.acme.email=${ACME_EMAIL}
      - --certificatesresolvers.le.acme.storage=/letsencrypt/acme.json
      - "--accessLog.format=json"
      - "--accessLog.filePath=/log/traefik.log"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./_log/traefik:/log:rw
      - ./_data/letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - traefik
    restart: unless-stopped
    env_file:
        - .env

  mosquitto:
    image: eclipse-mosquitto:2.0
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mqtt.rule=Host(`${DOMAIN_NAME}`) && Header(`Upgrade`,`websocket`)"
      - "traefik.http.routers.mqtt.entrypoints=websecure"
      - "traefik.http.routers.mqtt.tls=true"
      - "traefik.http.services.mqtt.loadbalancer.server.port=9001"
    volumes:
      - ./config:/mosquitto/config
      - ./_log/mosquitto:/mosquitto/log:rw
      - ./_data/mosquitto:/mosquitto/data:rw
    networks:
      - traefik
    restart: unless-stopped
    env_file:
      - .env

  nginx:
    image: nginx:latest
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.monolith.rule=Host(`${DOMAIN_NAME}`)"
      - "traefik.http.routers.monolith.entrypoints=websecure"
      - "traefik.http.routers.monolith.tls=true"
      - "traefik.http.routers.monolith.tls.certresolver=le"
      - "traefik.http.services.monolith.loadbalancer.server.port=7000"
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./web:/var/public
    networks:
      - traefik
    restart: unless-stopped
    env_file:
      - .env

networks:
  traefik:
    external: true
