name: monolith-v2

services:
  traefik:
    image: traefik:3.4
    profiles:
      - with_traefik
    command:
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80/tcp
      - --entrypoints.websecure.address=:443/tcp
      - --entrypoints.websecure.http.tls.certresolver=le
      - --certificatesresolvers.le.acme.tlschallenge=true
      - --certificatesresolvers.le.acme.email=${ACME_EMAIL}
      - --certificatesresolvers.le.acme.storage=/letsencrypt/acme.json
      - "--accessLog.format=json"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./_data/letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - traefik
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    env_file:
      - .env

  init-log:
    image: busybox:latest
    command: sh -c "touch /log/server.log && chmod 666 /log/server.log"
    volumes:
      - ./_log:/log:rw
    restart: "no"

  mosquitto:
    image: eclipse-mosquitto:2.0
    depends_on:
      init-log:
        condition: service_completed_successfully
    volumes:
      - ./config:/mosquitto/config
      - ./_log:/log:rw
      - ./_data/mosquitto:/mosquitto/data:rw
    networks:
      - traefik
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    env_file:
      - .env

  nginx:
    image: nginx:latest
    depends_on:
      init-log:
        condition: service_completed_successfully
    command: /bin/sh -c 'printf "%s" "$$ANNOUNCEMENT" > /tmp/announcement && exec nginx -g "daemon off;"'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.monolith-v2.rule=Host(`${DOMAIN_NAME}`)"
      - "traefik.http.routers.monolith-v2.entrypoints=websecure"
      - "traefik.http.routers.monolith-v2.tls=true"
      - "traefik.http.routers.monolith-v2.tls.certresolver=le"
      - "traefik.http.services.monolith-v2.loadbalancer.server.port=7000"
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ../web/dist:/var/public
      - ./_log:/log:rw
    networks:
      - traefik
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    env_file:
      - .env

networks:
  traefik:
    external: true
