name: ESP-IDF Firmware Build

on:
  push:
    paths:
      - 'device/firmware/**'
  workflow_dispatch:

jobs:
  build:
    name: Build firmware
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: v5.5
          target: esp32s3
          path: 'device/firmware'

      - run: |
          mkdir -p release/bootloader
          cp device/firmware/build/flash_args release
          cp device/firmware/build/monolith.* release
          cp device/firmware/build/bootloader/bootloader.* release/bootloader
          cp -r device/firmware/build/partition_table release

      - uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: release
