name: ESP-IDF Firmware Build

on:
  push:
    paths:
      - 'device/firmware/**'
  workflow_dispatch:

jobs:
  build:
    name: Build firmware
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: v5.5
          target: esp32s3
          path: 'device/firmware'

      - uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: device/firmware/build/monolith.*
